---
# tasks file for php-apache

- name: install packages
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - php 
    - libapache2-mod-php
    - php-mysql
    - php-curl
    - php-cgi
    - 
  notify:
    - restart apache2

- name: copy Index.php
  template:
    src: index.php.j2
    dest: /var/www/html/index.php

